yldio/yld.io

.babelrc
.circleci/config.yml
.eslintignore
.jest/__mocks__/fileMocks.js
.jest/jestPreprocess.js
.jest/loaderShim.js
.jest/registerContext.js
jest.config.js
package.json
src/components/Homepage/specialty.js
src/components/Service/work-stage/alternatives.js
src/components/Service/work-stage/elements.js
src/components/pagePaths.js
src/pages/contact.js
stories/__snapshots__/storyshots.test.js.snap
stories/storyshots.test.js
yarn.lock

Making a separate PR so I can pivot to work on a bug and continued test writing can be done on another PR.

Sets up the environment for storyshot tests

---

src/components/Common/topCaseStudy.js
src/components/Footer/office.js
src/components/Homepage/blog.js
src/components/Homepage/events.js
src/components/Homepage/jobs.js
src/components/Typography/h1.js
src/components/Typography/h3.js
src/components/Typography/h4.js
src/components/Typography/h5.js
src/components/Typography/h6.js
src/templates/caseStudy.js
src/templates/service.js
src/utils/theme.js
stories/__snapshots__/storyshots.test.js.snap

https://trello.com/c/GcZ4qmku/127-update-typescale

Update type scale

---

src/components/GrayBG.js

prev PR fixed canon page but not other pages where problem was occuring

gray bg overflow fix

---

.circleci/config.yml
src/components/Common/CookieBanner.js
src/components/layout.js
src/tests/lighthouse.test.js

Creates the cookie notification for the current grid.

Cookie notification

---

gatsby-node.js
src/components/Common/CookieBanner.js
src/pages/case-study/canon-giving-stories-a-new-form.js
src/pages/contact.js
src/templates/policy.js
src/utils/makeText.js

Creates policy template, which with the content now added on contentful creates the privacy, cookie, and data retention policies. 

Privacy policy and such

---

src/components/Homepage/caseStudy.js
src/components/Typography/h1.js
src/components/grid.js
src/components/layout.css
src/pages/index.js
stories/__snapshots__/storyshots.test.js.snap

updated the case study preview component to be close to design spec

Case study preview tweaks

---

src/components/Homepage/events.js
src/components/Speciality/blog.js
src/components/Speciality/books.js
src/components/Speciality/community.js
src/components/Speciality/events.js
src/components/Speciality/projects.js
src/components/Speciality/talks.js
src/components/Speciality/tutorials.js
src/components/posts.js
src/pages/contact.js
src/templates/speciality.js
src/utils/makeBlogPosts.js

[Trello ticket](https://trello.com/c/IOTnoXXX/57-react-seo-page)
[Trello ticket](https://trello.com/c/Xyi49MwZ/59-kubernetes-seo-page)
Adds two new more SEO pages and makes several changes to components to make them more dynamic 

add seo pages

---

src/components/Homepage/assets/homepage-event-icon.svg
src/components/Homepage/events.js
src/components/Homepage/jobs.js
src/components/Homepage/specialty.js
src/components/Typography/h3.js
stories/__snapshots__/storyshots.test.js.snap

the qa detailed in the above ticket, plus adding margin to the top of the featured event image

homepage QA

---

src/components/Homepage/specialty.js

fix firefox

---

src/components/Homepage/services.js
src/pages/index.js

rename speciality to services

---

gatsby-node.js
src/components/Speciality/projects.js
src/components/Speciality/talks.js
src/pages/index.js
src/templates/service.js
src/templates/speciality.js

Closes
https://trello.com/c/oWYKiekC/284-fix-issues-that-greta-was-having-with-entering-info-from-seo-copy-documents-into-contentful
and 
https://trello.com/c/kFZ3rLFQ/285-re-order-the-case-study-cards-in-the-seo-page-so-the-first-case-study-is-to-the-left-of-the-related-projects-title

remove unused code

---

gatsby-node.js
src/components/Speciality/training.js
src/components/pagePaths.js
src/pages/case-study/_stackable-rebranding-the-orginal-cloud.js
src/pages/case-study/canon-giving-stories-a-new-form.js
src/pages/case-study/joyent-bringing-application-awareness-to-cloud.js
src/pages/index.js
src/pages/our-work.js
src/templates/caseStudy.js
src/templates/service.js
src/templates/speciality.js

Fix master things
Closes https://trello.com/c/BsrvTKUX/288-request-nodejs-training-link-issues-seo-page

fix master

---

.eslintignore
src/components/Common/Hr.js

closes **https://trello.com/c/ldI86Vmv/322-tests-failing-on-master-branch**

add public to eslintignore

---

src/components/Common/CaseStudyCards/CaseStudyHero.js
src/components/Common/seoLinks.js
src/components/Homepage/seoText.js
src/components/OurWork/CaseStudy.js
src/components/Speciality/blog.js
src/components/Speciality/books.js
src/components/Speciality/community.js
src/components/Speciality/events.js
src/components/Speciality/talkToUs.js
src/components/Speciality/talks.js
src/components/Speciality/training.js
src/components/Speciality/tutorials.js
src/components/Typography/h1.js
src/components/Typography/h2.js
src/components/Typography/index.js
src/components/forms.js
src/components/styledLink.js
src/pages/404.js
src/pages/case-study/canon-giving-stories-a-new-form.js
src/pages/contact.js
src/pages/our-work.js
src/templates/service.js
stories/__snapshots__/storyshots.test.js.snap
stories/index.stories.js

Closes https://trello.com/c/bVAB5XQc/248-replace-withcomponent-calls-with-as-prop-on-styled-components

Remove withCompoent

---

src/pages/training.js

fix case study in training

---

README.md
package.json
src/components/Training/Courses.js
src/components/Training/Modal.js
src/pages/training.js

Current Model is:
A training page has training categories and then each category has courses inside

review cats

---

src/components/Common/SubtitleWithBody.js
src/components/Common/TitleAndList.js
src/components/JoinUs/elements.js
src/components/Training/Modal.js
src/pages/training.js
stories/__snapshots__/storyshots.test.js.snap
stories/subtitleAndBody.stories.js

Add new `description` field on the course info and created the `SubtitleAndBody` component.

feat: add description to course and create SubtitleAndBody component

---

src/components/Header/index.js

fix: open topnav blog link on a new tab

---

src/components/Homepage/services.js

put a short summary of what you did here

fix: fix stagger on masonry link hover animation

---

src/components/Header/elements.js

responsive fix in the menu

---

src/pages/case-study/_stackable-rebranding-the-orginal-cloud.js
src/pages/case-study/canon-giving-stories-a-new-form.js
src/templates/caseStudy.js

remove more of our work

---

src/templates/service.js

fix: fix image query on service

---

src/components/Common/Tab.js
src/components/Common/UnstyledButton.js
src/components/Header/elements.js
src/components/Training/Modal.js
src/components/styledLink.js
src/utils/theme.js
stories/__snapshots__/storyshots.test.js.snap
stories/tab.stories.js

Created Tab component and storybook stories

feat: add Tab Component

---

src/pages/contact.js

sneaky letters got in here :scream:

remove random 'kk' letters from the Contact page

---

stories/__snapshots__/storyshots.test.js.snap
stories/typography.stories.js

Before, it took around 80s, after this change it now takes around 40s. It's still a bit too much, but it's an improvement.

fix: simplify typography stories

---

src/components/Header/Hamburger.js
src/components/Header/HeaderAnchor.js
src/components/Header/Navbar.js
src/components/Header/index.js
src/images/menu.svg
stories/__snapshots__/storyshots.test.js.snap

Fix hamburger color and some mobile menu issues

fix: fix hamburger color and some mobile menu issues

---

src/components/AboutUs/StaffCard.js
src/components/AboutUs/Teams.js
src/components/Common/Tab.js
src/pages/about-us.js
stories/__snapshots__/storyshots.test.js.snap
stories/staffCard.stories.js

Building the Teams section for the About us page

feat: about us page - teams section

---

src/components/Header/index.js

Teeny requested change from Greta

make 'Us' in 'Join Us' lowercase on the navbar

---

src/pages/index.js

fix: remove company logo blur and add a fade-in

---

src/components/Footer/links.js

Update Behance link to https://www.behance.net/YLDio

feat: update behance link

---

src/components/Header/TopNav/Dropdown.js

fix: small fix on desktop dropdown

---

src/components/Header/TopNav/Dropdown.js
src/components/Header/TopNav/InnerAnchorItem.js
stories/__snapshots__/storyshots.test.js.snap

fix: remove unneeded callback on dropdown item

---

src/components/Footer/links.js

update dribble link

---

src/components/Common/BaseVideoLink.js
src/components/Common/GreyBackground.js
src/components/Common/Hr.js
src/components/Common/StyledLink.js
src/components/Footer/elements.js
src/components/Header/SideNav/Dropdown.js
src/components/Header/SideNav/InnerAnchorItem.js
src/components/Header/TopNav/Dropdown.js
src/components/Header/TopNav/InnerAnchorItem.js
src/utils/globalStyle.js
src/utils/theme.js
stories/__snapshots__/storyshots.test.js.snap
stories/colors.stories.js

I guess there's no Trello card for this, but this is just me scratching an itch that I had. 
Always felt that having a story for our color variables is easy to do and makes sense. 
Also, I think that having directly the HEX code on the theme variables makes it harder to reason about and to reuse colours for more than one variable, so I moved them outside and named them — as well as I could — based on [this](https://app.zeplin.io/project/5b4e666f0d4230a16dffd93a/screen/5c61564dd958777e20e8faec).

feat: color story

---

.circleci/config.yml
README.md
docs/scripts.md
tests/e2e/training-page.test.js

- pass a different port than the one used by lighthouse(3001) to createServer for Testcafe(3002)
- remove styling inconsistency in circleci config
- remove unneeded build command in circleci config for test:lighthouse since it is now part of the script.
- Update readme and docs/scripts with Testcafe information

feat: update testcafe configuration and information

---

src/pages/contact.js

Update copy and remove placeholder in contact form

---

.eslintignore
.eslintrc
src/components/AboutUs/StaffCard.js
src/components/Common/seoLinks.js
src/components/Footer/Locations.js
src/components/Footer/Office.js
src/components/Header/SideNav/Dropdown.js
src/components/Header/SideNav/OuterAnchorItem.js
src/components/JoinUs/Work.js
src/components/JoinUs/elements.js
src/components/LatestPosts.js
src/components/Service/getSections.js
src/components/Speciality/Events.js
src/components/Speciality/Talks.js
src/components/grid.js
src/functions/lever.js
src/functions/meetup.js
stories/__snapshots__/storyshots.test.js.snap
tests/e2e/sideNav-dropdown-test.js
tests/e2e/topNav-dropdown-test.js
tests/e2e/training-page-test.js

Codebase had a bunch of unused vars everywhere, this PR changes this and adds an eslint rule to make sure it doesn't happen

add no-unused-vars, fix code

---

src/components/grid.js
stories/__snapshots__/storyshots.test.js.snap

changes in this PR created issues on the site with duplicate content https://github.com/yldio/yld.io/pull/219

revert changes to grid utils

---

src/functions/lever.js

Lambda was returning `"Class constructor URL cannot be invoked without 'new'".` so just need to format the URL properly

Fix lever url

---

src/pages/open-source.js

Oops! Left this in here
Should have been done as part of https://github.com/yldio/yld.io/pull/228

remove slug from graphql query

---

src/pages/open-source.js

Apologies. It's late on a Friday afternoon :sweat:

more removals of the 'slug' from Contentful

---

src/components/Common/Statement.js
src/components/Common/TitleAndList.js
src/components/OpenSource/WhyOpenSource.js
stories/__snapshots__/storyshots.test.js.snap
yarn.lock

Trello Tickets -
[WhyUseOpenSource](https://trello.com/c/6bf4cfEm/484-why-use-open-source-component)
[CaseStudyPreview](https://trello.com/c/aV5AxR0t/529-add-casestudypreview-statement-components-to-open-source-page)
This PR fixes points made in both tickets by James

update WhyOpenSource and TitleAndList

---

src/components/Common/seoLinksContainer.js
src/pages/open-source.js
src/templates/service.js

Open source technologies section

---

src/components/Footer/index.js

Fix typos in footer index

---

src/components/Common/Events.js
src/components/Common/Repo/Repo.js
src/components/Common/seoLinks.js
src/components/Common/seoLinksContainer.js
src/components/OpenSource/Contributions.js
src/components/OpenSource/OpenDeliverables.js
src/components/OpenSource/WhyOpenSource.js
src/pages/open-source.js
stories/__snapshots__/storyshots.test.js.snap

Updates to all tickets below
[why use open source](https://trello.com/c/6bf4cfEm/484-why-use-open-source-component)
- Padding update to bottom of section
[upcoming events](https://trello.com/c/tLZy8Bj4/530-upcoming-events-section-for-os-page )
- Align title and event list
- Add description
- Change title
- Remove cta as requested by James
[github deliverables](https://trello.com/c/rS48DfwP/518-github-repo-related-work-open-deliverables-contributions-sections-lambda)
- Change spacing between CTA
- Update colour of repo text and HR

Open source styling updates

---

src/components/Common/BaseVideoLink.js
src/components/Common/Repo/Repo.js
src/components/OpenSource/Contributions.js
src/components/OpenSource/OpenDeliverables.js
src/components/OpenSource/WhyOpenSource.js
src/pages/open-source.js
stories/__snapshots__/storyshots.test.js.snap

put a short summary of what you did here

lines styling

---

src/components/Common/Events.js
src/components/Common/Repo/Repo.js
src/components/Common/Repo/RepoWithImage.js
src/components/OpenSource/Contributions.js
src/components/OpenSource/OpenDeliverables.js
src/components/OpenSource/WhyOpenSource.js
src/pages/open-source.js
stories/__snapshots__/storyshots.test.js.snap

https://trello.com/c/rS48DfwP/518-github-repo-related-work-open-deliverables-contributions-sections-lambda 
https://trello.com/c/tLZy8Bj4/530-upcoming-events-section-for-os-page https://trello.com/c/6bf4cfEm/484-why-use-open-source-component

Section styling updates

---

src/components/OpenSource/Partnerships.js

set ratiocontainer on logos, set max-width on parent

os partnerships logo fix

---

package.json
src/components/Common/StyledLink.js
src/components/JoinUs/OpenPositions.js
src/components/JoinUs/ViewOpenPositions.js
src/pages/join-us.js
yarn.lock

Added a scroll to component to ensure that each and every click on Show Vacancies WILL get the user to the vacancies section. The internal # linking wasn't working reliably.

F same page link

---

.storybook/config.js
package.json
src/components/Header/TopNav/Dropdown.js
src/components/Header/TopNav/OuterAnchorItem.js
src/components/Header/TopNav/index.js
stories/__snapshots__/storyshots.test.js.snap
yarn.lock

It appears I've introduced some bugs to the header in PR #263, from looking at history it appears the header dropdown has had quite a lot of fuss over it already. I've created a ticket to address the entire dropdown functionality in general, for the time being I'm going to revert the changes and come back to it later.

revert changes to header from SEO Updates PR

---

src/components/Common/Head.js
src/components/ContactUs/TitleSection.js
src/images/service-speciality-logo.js
src/pages/case-study/canon-giving-stories-a-new-form.js
src/pages/case-study/joyent-bringing-application-awareness-to-cloud.js
src/pages/join-us.js
src/pages/open-source.js
src/pages/our-work.js
src/templates/trainingCourseModal.js
tests/e2e/training-page-test.js

Make sure we  have SEO descriptions, titles are aligned properly and h1s are present

SEO updates

---

src/functions/lever.js

Fixes the lever lambda by creating the url with `new URL(...)`

correctly parse URL

---

src/components/Common/Head.js

change attribute name for og:image 🤦🏼‍♂️

---

gatsby-config.js
package.json
yarn.lock

This adds the gatsby netlify plugin - https://www.gatsbyjs.org/packages/gatsby-plugin-netlify/
TLDR it adds headers to assets marked as prefetch in gatsby to enable h2 pushing

add netlify plugin

---

package.json
src/templates/speciality.js
yarn.lock

added lodash inNull checker for building info in speciality to prevent error on build when it runs into null

Fix speciality error on null

---

src/components/Common/ExternalAnchor.js
src/components/Common/StyledLink.js
stories/__snapshots__/storyshots.test.js.snap

Added [Gatsby GA Outbound Link](https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/#outboundlink-component) to our Links.

added GA Outbound Link to track out leavers

---

src/components/Header/navLinksHelper.js

For some reason react native displays design, this logic has been removed in the landing page updates so this is a very short lasting change 
https://www.yld.io/speciality/react-native/

HOTFIX: add react-native to engineering services

---

src/templates/speciality-component.js
stories/__snapshots__/storyshots.test.js.snap

tiny typo that prevents blogs from rendering.

613 Speciality page blogs

---

src/components/Header/TopNav/LogoLink.js

Make homepage link clickable again

---

src/components/Common/CaseStudyCards/CaseStudyBlocks.js
src/pages/case-study/central-working-changing-how-you-work.js

Put a short summary of what you did here:
See trello

583-central-working-outcome-section

---

src/functions/oss/meta.js
tests/unit/lambdas/lever.test.js
tests/unit/lambdas/meta.test.js
tests/unit/lambdas/repos.test.js

Github lambda - Meta util test

---

package.json

Put a short summary of what you did here:
Temporary resolution to update to "sharp": "0.22.1" which works locally and on CI 🎉 

Fix sharp package version

---

src/pages/index.js
src/templates/speciality.js

Put a short summary of what you did here:
Populate Homepage with the new seoMetaData.
Retrieve seoMetaData data within homepage and pass to Head

Retrieve seoMetaData data within homepage and pass to Head

---

package.json
src/components/Common/Head.js
src/fragments/index.js
src/pages/case-study/canon-giving-stories-a-new-form.js
src/pages/case-study/central-working-changing-how-you-work.js
src/pages/case-study/doctorlink-setting-up-a-design-system.js
src/pages/case-study/joyent-bringing-application-awareness-to-cloud.js
src/pages/case-study/learnerbly-accelerating-professional-growth.js
src/templates/caseStudy.js

Add SEO Meta Data fields to all case study templates and pages

644 - SEO Meta Data - Case Studies

---

src/pages/about-us.js

Populate About us page with the new seoMetaData.
Retrieve seoMetaData data within about us page and pass to Head

Retrieve seoMetaData data within about us page and pass to Head

---

src/pages/join-us.js

Populate join us page with the new seoMetaData.
Retrieve seoMetaData data within join us page and pass to Head

Retrieve seoMetaData data within join us page and pass to Head

---

gatsby-node.js
src/components/Speciality/HowWeWorkWith.js
src/templates/speciality/schemas.js
yarn.lock

Opening PR for deploy preview so James can take a look

update how we work section with new typography

---

gatsby-node.js
package.json
src/components/CareerFramework/Discipline.js
src/components/CareerFramework/Group.js
src/components/CareerFramework/Join.js
src/components/CareerFramework/Level.js
src/components/CareerFramework/index.js
src/components/Common/StyledLink.js
src/components/Footer/index.js
src/pages/career-framework.js
src/templates/career-discipline.js
static/_redirects
stories/__snapshots__/AboutUs.stories.snapshot
stories/__snapshots__/BlogListing.stories.snapshot
stories/__snapshots__/ConferenceCard.stories.snapshot
stories/__snapshots__/EventCard.stories.snapshot
stories/__snapshots__/Specialty.stories.snapshot
stories/__snapshots__/TitleAndList.stories.snapshot
stories/__snapshots__/TitleAndMediaList.stories.snapshot
stories/__snapshots__/caseStudy.stories.snapshot
stories/__snapshots__/getInTouch.stories.snapshot
stories/__snapshots__/statementComponent.stories.snapshot
yarn.lock

Creates career framework page and corresponding components

Career framework

---

src/components/Service/WorkStage.js
yarn.lock

Insert icon container width fixed dimensions to avoid vertical misalignments.
Followed [this spec](https://app.zeplin.io/project/5b4e666f0d4230a16dffd93a/screen/5c3333738c1616af522980be) to determine container dimensions.

fix(637): add icon container on service page

---

package.json
src/components/AboutUs/StaffCard.js
src/components/AboutUs/__tests__/__snapshots__/Teams.test.js.snap
src/components/ContactUs/Map.js
src/components/ContactUs/Marker.js
src/components/ContactUs/mapStyles.js
src/components/Footer/index.js
src/components/Typography/BodyPrimary.js
src/components/layout.js
src/pages/contact.js
src/utils/getLatLngMidpoint.js
stories/__snapshots__/AboutUs.stories.snapshot
stories/__snapshots__/Specialty.stories.snapshot
stories/__snapshots__/staffCard.stories.snapshot
yarn.lock

- Remove old page
- Add new page!

669 contact us page

---

src/components/Common/GetInTouch.js
src/components/Events/ConferenceCard.js
src/components/Events/EventCard.js
src/pages/events.js
stories/__snapshots__/ConferenceCard.stories.snapshot
stories/__snapshots__/EventCard.stories.snapshot
stories/__snapshots__/getInTouch.stories.snapshot

Missed a few things!  See ticket for Luis checkpoints

event card and conference card updates

---

src/components/Common/GetInTouch.js
stories/__snapshots__/getInTouch.stories.snapshot

[Trello ticket](https://trello.com/c/h1fTcHCt/680-talk-to-someone-component-get-in-contact-in-mobile-view)

680 - Get in touch mobile view 

---

src/pages/events.js

- Change media queries for events hero image height for mobile

683 - fix events page hero image on mobile

---

src/pages/contact.js

- update grid values for office locations

682 - Fix office locations on mobile view

---

src/components/Blog/MediumPostPreview.js

This HOTFIX 🔥is a temporary solution and will be removed once the blog migration has been completed

prevent null subtitle breaking build

---

src/components/Homepage/OurWork.js
src/fragments/index.js
src/pages/join-us.js
src/pages/our-work.js
src/templates/service.js
src/templates/speciality.js

(And add some for v2)
Should allow us to delete the old content type

remove uses of NonTemplatedCaseStudy v1

---

src/pages/index.js

remove last ContentfulNonTemplatedCaseStudy reference

---

src/templates/policy.js

This should be the final one for 690, Contentful already has the policies in md

remove policy section and style policy body

---

gatsby-node.js
src/components/Blog/BlogPostPreview.js
src/components/Homepage/BlogSection.js
src/templates/blog.js

fixes /blog history entry being
https://trello.com/c/Y4zJcgXd/716-blog-post-launch-tasks

consistent leading / trailing slashes in paths

---

src/components/Blog/Typography.js
stories/__snapshots__/BlogTypography.stories.snapshot

Check out e.g. `/easier-graphql-wrappers-for-your-rest-apis/`

larger iframes in blog posts

---

src/components/Common/seoLinksContainer.js

Update 'We work with' section alignment

---

package.json
src/components/Blog/Instagram.js
src/components/Blog/Typography.js
src/functions/blogMethods/custom-mdx/__tests__/transform-iframes.test.js
src/functions/blogMethods/custom-mdx/transform-iframes.js
src/functions/blogMethods/custom-mdx/upload-image-to-contentful.js
src/functions/blogMethods/export-from-local-xml.js
src/functions/blogMethods/index.js
src/templates/blog-post.js
stories/__snapshots__/BlogTypography.stories.snapshot
yarn.lock

Blog instagram embeds

---

static/_redirects

update netlify redirects

---

src/components/Homepage/Intro.js
tests/lighthouse/lighthouse.js

fix listitem audit

---

src/components/AboutUs/__tests__/__snapshots__/Teams.test.js.snap
src/components/Common/Image.js
src/components/Homepage/Intro.js
src/components/Homepage/OurWork.js
stories/__snapshots__/AboutUs.stories.snapshot
stories/__snapshots__/BackgroundGraphic.stories.snapshot
stories/__snapshots__/ConferenceCard.stories.snapshot
stories/__snapshots__/Specialty.stories.snapshot
stories/__snapshots__/TitleAndList.stories.snapshot
stories/__snapshots__/WhyOpenSource.stories.snapshot
stories/__snapshots__/caseStudy.stories.snapshot
stories/__snapshots__/getInTouch.stories.snapshot
stories/__snapshots__/image.stories.snapshot
stories/__snapshots__/staffCard.stories.snapshot
tests/lighthouse/lighthouse.js

I am not sure if any of this actually helps with the audit result, it seems like this might just be a false positive, our image loading already seems very well optimized.

optimize image loading

---

src/components/Common/seoLinks.js
src/components/Homepage/services.js
tests/lighthouse/lighthouse.js

fix tap targets being too close to each other

---

tests/e2e/topNav-dropdown-test.js
tests/e2e/training-page-test.js
tests/lighthouse/lighthouse.js

This doesn't exactly make the e2e tests prettier (they're already using
stuff like testid which is not ideal), but it's better than nothing

stabilize e2e

---

README.md
docs/blog.md
gatsby-config.js
package.json
src/components/Common/Anchor.js
src/components/Common/CaseStudy.js
src/components/Common/CookieBanner.js
src/components/Common/GetInTouch.js
src/components/Common/InternalAnchor.js
src/components/Common/StyledLink.js
src/components/Common/TitleAndMediaList.js
src/components/Common/__tests__/InternalAnchor.test.js
src/components/Common/animatedLink.js
src/components/Common/seoLinks.js
src/components/Footer/FooterLinks.js
src/components/Footer/links.js
src/components/Header/DesktopNav/LogoLink.js
src/components/Header/DesktopNav/ServiceLink.js
src/components/Homepage/OurWork.js
src/components/Homepage/services.js
src/components/Training/course/ModalCloseButton.js
src/components/layout.js
src/functions/blogMethods/__tests__/transform-html-to-markdown.test.js
src/functions/blogMethods/__tests__/validate-mdx.test.js
src/functions/blogMethods/custom-mdx/__tests__/transform-strings.test.js
src/functions/blogMethods/custom-mdx/transform-strings.js
src/utils/google-json.json
stories/JobLink.stories.js
stories/TitleAndMediaList.stories.js
yarn.lock

* http instead of https
* yld.io instead of www.yld.io
* missing trailing slash (ensured by InternalAnchor component)
https://trello.com/c/NUpZHUXR/727-3xx-4xx-links

avoid links that 3xx

---

src/fragments/index.js
src/pages/case-study/canon-giving-stories-a-new-form.js
src/pages/case-study/central-working-changing-how-you-work.js
src/pages/case-study/doctorlink-setting-up-a-design-system.js
src/pages/case-study/joyent-bringing-application-awareness-to-cloud.js
src/pages/case-study/learnerbly-accelerating-professional-growth.js
src/templates/caseStudy.js

https://trello.com/c/95KLbd9p/741-featured-related-work-component-has-not-been-updated-at-the-bottom-of-case-studies

use FeaturedWork component for related case studies

---

package.json
src/functions/blogMethods/custom-mdx/__tests__/add-frontmatter.test.js
src/functions/blogMethods/custom-mdx/add-frontmatter.js
yarn.lock

Yaml stringify frontmatter metadata to prevent it from breaking the build

fix: post frontmatter

---

src/utils/google-json.json

Add other office locations to json-ld schema.org

[SEO] - Add other ofices locations

---

src/components/Header/utils/navLinks.js
src/pages/contact.js

Add missed headres from contact page and change link name from "our team" to "about us"

Add missed headers 

---

src/components/Common/Tab.js

Fix tab active and focus style

fix active tab style

---

gatsby-config.js
gatsby-node.js
package.json
src/html.js
yarn.lock

Set webpack to production mode and prefetch google fonts

Performance improvement #1

---

gatsby-config.js
package.json
yarn.lock

Added the RSS Feed into the website. The content of the RSS Feed is the news from the blog of the website (https://www.yld.io/blog/).

feat: add rss feed
