src/components/GrayBG.js
For some reason negative z-indexes always make things unclickable. ¯\\\_(ツ)\_/¯
=> change negative z-index to positive

src/components/GrayBG.js
give following element higher z-index when using offsetBottom on GrayBG
=> fix canon page (/gray bg generally)

.github/pull_request_template.md
Unfortunately you can currently not make a template for PR reviews, but this creates a template for the PR body, which includes a checklist for the reviewers to fill out. 
By obvious bugs I mean that I don't expect the reviewer to do proper thorough manual QA, but I do expect them to notice any obvious problems, especially the kind that would be obvious for the user.
Would love input / feedback on the content, and it can of course evolve as we decide what is necessary 😃
=> add review / PR template

package.json, yarn.lock
I ran `yarn upgrade`, after doing `yarn list event-stream flatmap-stream` we no longer have the tainted deps in the tree. 
Have run the app and it seems ok too.
=> remove vulnerability from deps

src/components/Common/animatedLink.js, src/components/Homepage/specialty.js
the image for canon was stretched in the speciality section - this fixes it so it's closer to the designs and generally isn't broken on all 3 breakpoints.
=> fix image stretch home page mobile

src/components/Speciality/blog.js, src/components/Speciality/books.js, src/components/Speciality/community.js, src/components/Speciality/events.js, src/components/Speciality/intro.js, src/components/Speciality/projects.js, src/components/Speciality/talks.js, src/components/Speciality/training.js, src/components/Speciality/tutorials.js, src/templates/speciality.js
Just picked a single spelling - the one we use in Contentful so we don't have to change the content model
=> use 'speciality' everywhere, remove instances of 'specialty'

src/pages/case-study/canon-giving-stories-a-new-form.js
Live website ([Canon case study](https://www.yld.io/case-study/canon-giving-stories-a-new-form/)) has 'intro sentence' where first paragraph should be:
Supposed to be:
I've changed the content in Contentful, published but not yet deployed. This is the necessary change to the codebase, in order to reflect the content alterations
=> grab first paragraph from Contentful for canon case study (instead of intro sentence)

src/pages/case-study/joyent-bringing-application-awareness-to-cloud.js
The first paragraph on the Joyent case study ("In the early fall of..."), was entered into Contentful as `introSentence`. So, in the codebase, we are fetching the intro sentence for this page.
But this is incorrect. The `introSentence` field should be used for the "featured case study" component, or the case study cards that are going on the Our work page. Whereas, "In the early fall of..." should be entered into Contentful as `genericText1`
So I've changed the content in Contentful, published (but not yet deployed).
This PR contains the necessary change to the codebase, in order to reflect the content alterations
=> grab first paragraph from Contentful for Joyent case study (instead of intro sentence)

src/components/Header/index.js, src/components/layout.js, src/pages/404.js, src/pages/case-study/_stackable-rebranding-the-orginal-cloud.js, src/pages/case-study/canon-giving-stories-a-new-form.js, src/pages/contact.js, src/pages/index.js, src/templates/caseStudy.js, src/templates/policy.js, src/templates/service.js, src/templates/speciality.js
Currently we were checking if we were on the client side because we were using the `window.location.pathname` to do some logic. However, Gatsby injects the location as a prop on every page component. This way, we can pass our location to the `Layout` and from then to the `Header` component and use it safely with less checks.
I wish there was a way to also inject the location into the header directly but it doesn't seem like it.
Note: I ran `gatsby build` and served the build — everything looked ok.
Thoughts are welcome :)
=> fix: fix unnecessary client check on header

jest.config.js, src/components/Common/CompactVideoLink.js, src/components/Speciality/talks.js, src/images/button-play-dark.svg, src/images/button-play-light.svg, stories/__snapshots__/storyshots.test.js.snap, stories/compactVideoLink.stories.js
This PR aims to implement a reusable component called `CompactVideoLink` as documented here: https://app.zeplin.io/project/5b4e666f0d4230a16dffd93a/screen/5c3e05702c9f7852505e518f.
This component will be a dependency of a `StandaloneVideoLink` which will be used on the 'Join Us' page.
I created a storybook story for testing/checking the component in an isolated way.
This PR also fixes the following visual issue on the Talks component, it seems the different video links are not vertically aligned with each other.
(at least I think it's a bug @SaraVieira @jsms90 please shout if I'm wrong)
**Please note**: this MR adds 2 svgs for the play button (dark/light). I'm not comfortable with this, since the correct way to do this would be to have a single SVG for the icon, and change the `fill`s …
=> feat: add CompactVideoLink

src/components/Homepage/companies.js
Our build is breaking if there are no `companies` set up for the homepage, on the contentful. 
This code checks before trying to map through the collection..
=> fix: adding defensive code for missing companies collection on homepage

README.md
This documentation is based on the conversations that have happened on the attached trello ticket
@SaraVieira's has investigated our current IE situation. You can see a few issues on the screenshots below.
@carvil If we intend to start supporting IE, we may need to do a thorough audit of all the pages, raise tickets & add IE work to the roadmap so that it can be prioritised. What do you think?
=> add browser support section to readme

src/components/Header/elements.js, src/components/Header/index.js, src/images/close.svg, src/images/menu_close.svg
Fixing issue on close menu button on firefox.
Also, reused the close svg, since it was the same there's no need to have 2 files.
=> fix: fix close menu icon issue on firefox

src/components/Header/elements.js, src/components/Header/index.js
This PR fixes a couple of issues on our small tablet menu:
- the overlay didn’t react to clicks (it’s normal to dismiss the menu by clicking on the overlay)
- if we pay attention, when we close the menu,  the anchors jump around and cause an weird flicker
- I'm assuming that the overlay intention was to jump from the right as well as the menu
=> fix: fix weird flicker on small tablet menu

src/components/Common/talkToUs.js
When merging the Training page into the typography PR, I accidentally reintroduced the hard coded 'Talk to us' string - https://github.com/yldio/yld.io/pull/95/files#diff-32933ad3090bd956f8bb869dd0087893R17
So this has introduced the following bug to the live website:
This PR removes the hard-coded 'Talk to us' again
=> remove 'Talk to us' bug

src/components/AboutUs/PaddedCol.js, src/components/AboutUs/Partners.js, src/components/AboutUs/PartnersSection.js, src/components/AboutUs/Subsidiaries.js, src/pages/about-us.js
- Created `Partners` sub component for About Us page
- Re-used `PaddedCol` pattern from Subsidiaries section, but didn't use `ColumnLayout` this time
FYI, looks like this if a 5th gets added
---
---
=> Technology partnerships

src/components/Common/Button.js, src/components/Common/Forms.js, src/components/Common/Tab.js, src/components/Common/UnstyledButton.js, src/components/ContactUs/AreasOfInterest.js, src/components/ContactUs/ThankYouMessage.js, src/components/ContactUs/TitleSection.js, src/pages/404.js, src/pages/contact.js, stories/__snapshots__/storyshots.test.js.snap, stories/form.stories.js
- Moved title into its own section with white background - now using a prop to change the text of the title, instead of having one `SectionTitle` inside `Success` & one `SectionTitle` inside the form
- Deleted `Success` component & moved `BodyPrimary` (success message text) directly into render method
- Removed `Margin`s from around Grid & used same `Padding` pattern that we use on other pages
- Fixed spacing above & below grey section, for all breakpoints
Refactor along the way:
- Moved `forms.js` from `/components` into `/components/Common`
- Moved `Button` component out from `forms.js`, into its own file, since it is used on the 404 page too & could get used elsewhere in future (we don't have another Button component atm)
- Separate `TitleSection`, `ThankYouMessage` & `AreasOfInterest` …
=> Fix contact us page layout

src/components/AboutUs/AboutUsHero.js, src/pages/about-us.js
- Added "statement text" & "supporting statement" blocks to Contentful query  
(Note: the number of "supporting statements" is hard-coded in Contentful - see trello ticket for product reqs)
- Created component for hero section
---
FYI, I didn't use the `Statement` component after all because it turns out there a fair few fundamental differences:
|  | `Statement` component | `AboutUsHero` |
| -- | -- | -- |
| Background colour | Grey | White |
| Text colour | Grey | Black |
| Typography | `DisplayTitle` | `SectionTitle` (slight error in Zeplin designs for size on mobile, but I checked with Antonas) |
| Column width | <li>small tablet = 10</li><li>largeTablet = 10</li><li>desktop = 9</li> | <li>small tablet = 8</li><li>largeTablet = 10</li><li>desktop = 8</li> |
=> create AboutUsHero section & add necessary content fields to Contentful query

src/components/Training/Modal.js
=> Remove arbitrary restriction on training modal's bullet point - make full width of container instead

src/components/Training/Courses.js
Specified `width` prop on `<Image>` tag
It's likely that this bug was introduced with [this change to our Image component](https://github.com/yldio/yld.io/pull/139/files#diff-4e0a3b6f61abaa95f516fc7202464543R23), when the About us PR was merged
=> fix size of logos in 'Course catalog' section of training page

README.md, src/components/Training/Modal.js, src/tests/lighthouse.test.js
Bug:
Restricted width of image using prop on `Image` component
=> fix size of logos on training modal

src/components/Training/Modal.js
- remove width restriction from `CustomisedBulletpoint` on training page `Modal`
- instead restrict the width of the bullet points (and/or any other text) via the columns - i.e. bring Modal's column layout in line with design specs
=> training modals - fix column layout & remove width restriction on CustomisedBulletpoint

src/pages/training.js
Added missing `isTop` prop to the "related case study" on the training page, which puts top padding on the CaseStudy card.
=> add extra padding above related case study on training page

src/components/Common/StyledLink.js, src/components/Header/SideNav/Dropdown.js, src/components/Header/SideNav/InnerAnchorItem.js, src/components/Header/SideNav/outerItemStates.js, src/components/Header/TopNav/Dropdown.js, src/components/Header/TopNav/InnerAnchorItem.js, src/components/Header/TopNav/OuterAnchorItem.js, src/components/Header/TopNav/TopNavItem.js, src/components/Header/TopNav/index.js, src/components/Header/TopNav/outerItemStates.js, src/components/Header/TopNav/topNavItemStyles.js, src/components/Header/headerItemStyles.js, src/components/Header/outlineStyles.js, stories/__snapshots__/storyshots.test.js.snap
- The main issue of this ticket was due to a conflict between the `onMouseDown` and `onFocus` callbacks, which were affecting the same state. That was fixed.
Besides that, I improved some other scenarios:
- On Safari, there were some problems when trying to navigate by tabbing on the keyboard. This  was due to it not being able to transition the outline property. So in fact, the items were being focused, just the outline was not displaying corrrectly. Given that,  I've removed the outline transition.
- Also, I noticed that the `opacity: 0.5` rules were affecting the outline as well. Since it's not a good practice to reduce the opacity of the whole element just to get a lighter shade of the text color, I changed those rules to just use the lighter version of the text color (instead of …
=> fix: fix dropdown issues

src/templates/service.js
Using new field from contentful, that allows both templated and non templated case studies to be used on the engineering and design service pages
=> fix: Service pages to allow templated and non templated case studies

src/components/Header/TopNav/Dropdown.js, src/components/Header/TopNav/InnerAnchorItem.js, stories/__snapshots__/storyshots.test.js.snap
Console logging in Safari shows that `onMouseDown` does not fire on the InnerAnchorItem, when it is clicked.
Our understanding is that, onMouseDown propagates up to DropdownContainer, which changes the `isExpanded` prop (re-added in PR https://github.com/yldio/yld.io/pull/171). When this prop changes, the whole dropdown is re-rendered & navigation doesn't occur. Tbh we're unclear on what is different about Safari from other browsers, to cause this problem.
- revert PR https://github.com/yldio/yld.io/pull/172, which removed onMouseDown from InnerAnchorItem
- add `e.stopPropagation` on the inner anchor items, so that `isExpanded: !this.state.isExpanded` doesn't happen on an inner anchor click
=> fix bug: Dropdown links not navigating on safari

src/components/Header/SideNav/outerItemStates.js, src/components/Header/TopNav/Dropdown.js, src/components/Header/TopNav/outerItemStates.js, stories/__snapshots__/storyshots.test.js.snap
- switch styles for `hover` & `hoverAndActive` states (on both light and dark theme)
- change the styles that we use for "expanded" state of dropdown select button - now based on "hover" rather than "clickTap", so that it looks the same as the anchors next to it
- add bold font weight to active & active+hover
=> Navbar tweaks - change navbar item states' font colour & weight

stories/theme.js
Since our font family declarations are done in the `html.js` file (to speed up their fetching), they were not being added to the storybook stories. 
This PR fixes this issue.
=> fix: add font family styles to storybook

README.md, src/utils/theme.js, stories/__snapshots__/storyshots.test.js.snap, stories/spaces.stories.js
Having studied a bit the styling libs used in the project (styled-components, styled-system, styled-components-breakpoint, etc), I think they're really very powerful but we're not taking full advantage of them, namely on the `space scale` matter.
I just discovered last week that we have [this](https://app.zeplin.io/project/5b4e666f0d4230a16dffd93a/screen/5c0019f7e25494019fe389aa) documentation around our spacing rules, which is very handy for our spacing (margin/padding) definitions inside components.
Currently, we're defining spacing with the `styled-components-spacing` lib, which has `Margin` and `Padding` components. While — for some — this may simplify the space definition, I think it creates unnecessary levels of indentation and (worse) adds much more DOM nodes than we'd need. On top …
=> feat: add space to theme and documented it

src/components/Common/BaseVideoLink.js, stories/__snapshots__/storyshots.test.js.snap
- moved anchor within `BaseVideoLink` (used to build [Compact Video Link](https://app.zeplin.io/project/5b4e666f0d4230a16dffd93a/screen/5c5c152ac8862805cb930172) & [StandAlone Video Link](https://app.zeplin.io/project/5b4e666f0d4230a16dffd93a/screen/5c3e0570797c210e8b18b0d3)) to surround all of contents, including margins
- used `ExternalAnchor` instead of `a` tag
=> fix which area of the video components are clickable

src/components/Header/Hamburger.js, src/components/Header/TopNav/ServiceLink.js, src/components/Header/TopNav/index.js, src/components/Header/index.js, src/components/Header/navLinks.js, src/components/Speciality/Intro.js, src/components/layout.js, stories/TopNav.stories.js, stories/__snapshots__/storyshots.test.js.snap
nb: 
- there are 5 breakpoints to take into consideration as the topNav follow the structure of the main Layout.
- With the topNav being now positioned fixed, some other elements had to be adjusted depending on that change.
- The topNav header does not appear on Modal pages. So far only training pages have modals. I used a trainingModalRegExp to make sure that the header still renders on `training` or `training/#node-js` urls (which are navigation pages) but does not on a url such as `training/node` that is a modal. A bit confusing to read but easier to understand/see if you navigate on the deployed Netlify url.
Also done:
=> Topnav persistance on scrolling

src/components/AboutUs/Partners.js, src/components/Common/LogoGrid.js, src/components/Homepage/companies.js, src/components/Speciality/Projects.js, src/pages/index.js
Zeplin documentation for this component was created after the 'logo grids' on our website were built. This PR brings the existing pages in line with the Zeplin spec. It involves alterations to:
1. Statement/Companies section of the homepage
2. Projects section of all Speciality (aka SEO) pages
3. Technology Partnerships section of About Us page
This PR will:
- use the old `Companies` component from the homepage as the basis for a new `LogoGrid` component, now inside the Common folder
- alter this component to have 3 columns on small tablet (used to have 4 columns)
- add 12px spacing between each row of logos
- re-use this component on the Speciality template
- make the 'Other companies we helped' section of the Speciality template optional (i.e. remove this subtitle if/when there are no …
=> Implement LogoGrid Zeplin specs on live website

src/components/Speciality/Tutorials.js, src/templates/speciality.js
- Remove TutorialsSection from speciality pages that don't have any associated tutorials
- Fix description text, so that 'NodeJS' is no longer hard-coded into this section, regardless of which speciality page it's on
=> Fix tutorials section bug

src/components/Header/TopNav/ServiceLink.js, src/components/Speciality/Events.js, src/components/Speciality/assets/events-icon.svg, stories/__snapshots__/storyshots.test.js.snap
_nb: the actual filter that was in place was only filtering from date. There do not seem to be tags against an event so the filter I put in place looks for the speciality name within each event.eventTitle (case insensitive). If there is a better way, I'm open to suggestions._
=> Speciality-pages-events-section

src/components/Header/TopNav/Dropdown.js, stories/__snapshots__/storyshots.test.js.snap
When user double clicked on the Navbar drop down (only items that have dropdown were affected), the word got selected per standard browser functionality. This is a patch to disable that selection.
=> Fix "when user double clicks on dropdown select button, text is highlighted"

src/components/Homepage/events/FeaturedEvent.js, src/pages/index.js
- Altered the `Meetup Event` content type in Contentful - added a new field called `CTA Text`
- Added new `ctaText` field to graphql query for homepage
- Removed the hard-coded string: 'Visit the website' from our `FeaturedEvent` component and used `ctaText` instead
- Added 'Visit the website' inside the CTA Text field in Contentful, for the React JS Girls Conference event card (so that the live site doesn't break)
Note: once this is merged, I can safely publish the YLD Leadership Series event, which I've already added to Contentful.
=> Adjust FeaturedEvent component to allow CTA Text to be editable via Contentful

src/components/Header/SideNav/index.js, stories/__snapshots__/storyshots.test.js.snap
SideNav now scrollable on landscape views for Chrome.
=> Add scrollability to SideNav when height is not within window height

src/components/Header/navLinks.js, src/components/Header/navLinksHelper.js, src/pages/open-source.js, stories/__snapshots__/storyshots.test.js.snap
Open source link on navbar shouldn't be inside the 'services' dropdown. See Zeplin:
We don't need the `slug` field in Contentful - this is only used for templates:
=> Open source branch tweaks

package-lock.json, package.json, src/components/Common/CaseStudyCards/CaseStudyPreview.js, src/pages/open-source.js, yarn.lock
- add `slug` to open source page query, for use in the `CaseStudyPreview` component:
- added prop types to the `CaseStudyPreview` component to try and help engineers catch this kind of mistake in future
- added [`airbnb-prop-types` package](https://github.com/airbnb/prop-types) for the use of their `or` validator, which doesn't come with [`prop-types`](https://reactjs.org/docs/typechecking-with-proptypes.html) by default
=> Add featured case study slug to open source page query 

src/components/OpenSource/Contributions.js, src/pages/open-source.js
=> Open Source talks section updates

src/components/OpenSource/Partnerships.js, src/components/OpenSource/Talks.js
```
239px width and 108px high on desktop
This scales down to W165xH75px on Large Tablet
Then W200xH90px on Small Tablet and Mobile
```
=> Os partnerships section logos fix

gatsby-config.js
Passes props to the `react-modal` instance created by the `gatsby-plugin-modal-routing` plugin we're using to correctly setup the modals for their own routes. 
iOS Safari has some sort of issue with `position: fixed;` and `z-index`, or it's actually conforming to the spec, I forget. 
this PR overrides the default, `top`, `left`, `right`, `bottom` values that react-modal initialises with
=> Fix modal positioning

src/pages/case-study/doctorlink-setting-up-a-design-system.js, src/pages/index.js, src/templates/service.js
I added DoctorLink in that array in Contentul (which only has Canon so far). By updating to index 1 it renders the DoctorLink CS. If the intention is to always render 1 case study on Top, I suggest to leave index 0 and have a limitiation of `no more than 1` in Contentful, like it's done for related case studies.
I suggest that PR not to be merged before we have a chance to discuss this with the team.
nb:
Speaking of `services.relatedCaseStudy`, I tried and am still trying to add ContentfulNonTemplatedCaseStudyV2 as a fragment within the query. It's not having it. In Contentful related case study is set-up to potentially be of type ContentfulNonTemplatedCaseStudyV2 so I'm not sure what the problem is. I cannot update in Contentful as it would also …
=> Featured doctor link case study

src/components/Speciality/Projects.js, src/pages/case-study/canon-giving-stories-a-new-form.js, src/pages/case-study/joyent-bringing-application-awareness-to-cloud.js, src/pages/index.js, src/pages/our-work.js, src/pages/training.js, src/templates/caseStudy.js, src/templates/service.js, src/templates/speciality.js, yarn.lock
Updates all references to `introSentence as String` to `introSentence as Object` 
This fixes the differences in schemas across the case study templates where non templated case study was listed as `shortText` whereas the rest of the case study content types had `longText`.
This caused issues in the schema generation
=> update introSentence queries

src/components/Common/animatedLink.js, src/components/Homepage/services.js, stories/__snapshots__/storyshots.test.js.snap
- remove magic numbers for image dimensions
- resolve confusing naming for `PosterImage` in code base
=> Make case study card images full width of container

src/components/Common/Head.js
This is a bit of spike but I'm trying to work out if  the urls we get from contentful are causing twitter et al to not properly render them in cards. 
image asset url from contentful: `//image.ctfassets.com.....`
^ this doesn't render properly in twitter cards when set as `og:image` but `https://yld.io/image/logo.png` renders fine....
=> spike: prefix socialLogo with https

src/html.js
Google Fonts by default does not give us `font-display: swap` in it's style sheets, this gets flagged in lighthouse auditing: 
More details here: https://developers.google.com/web/updates/2016/02/font-display?utm_source=lighthouse&utm_medium=devtools
This PR simply passes the query param `&display=swap` to the url we use to get the fonts in the first place which then in turn gets us the font-display in all of the fonts downloaded
=> add query param to get font-display: swap in google fonts

src/components/Common/Anchor.js, src/components/Common/ExternalAnchor.js, src/components/Common/StyledLink.js, src/components/Common/animatedLink.js
We had all these warnings related to propTypes title in multiple pages.
Links seem to work without it so I'm not sure why it didn't show in the first place
put a short summary of what you did here
- Remove title as required propType and remove propType as a whole for StyledLink component
- Refactor StyledLink.js as a whole.
- Remove title as required propType and remove propType as a whole for ExternalAnchor component
=> Fix-react-warning-proptypes-title-required

gatsby-config.js, package.json, src/html.js, yarn.lock
This PR adds `gatsby-plugin-prefetch-google-fonts` to our plugins  in gatsby-config.  
The reason for this is to lower the time it takes for font files to be loaded on to the site. Using the <link> method it adds a step to fetch the CSS stylesheets and render to the site. This should give us some increase in performance, not huge but every little helps!
=> add google-font-prefetch plugin

src/templates/speciality.js
Added 
```   
fluid(maxWidth: 250) {
...GatsbyContentfulFluid_withWebp_noBase64
}
```
to the GQL query for speciality clients grid.
Now looks like this: 
=> added fluid query to Speciality GQL query for grid images

src/components/Header/TopNav/LogoLink.js, stories/__snapshots__/storyshots.test.js.snap
Rejigged the logic of providing the logo colour from two options (isService and isSpeciality) to three options (isService, isSpecialityWithOwnColour, isSpecialityWithoutOwnColour)
=> Fixed logic for YLD logo colours on speciality / service pages

src/components/JoinUs/ViewOpenPositions.js
We were importing the default export from StyledLink, I believe the `react scroll to` module we're using fires the react synthetic event after its finished its initial scrolling behaviour so an anchor click will go to its href which is undefined thus we saw 404!
=> Fixed JoinUs job ops redirecting to undefined

src/components/Common/animatedLink.js, src/templates/speciality-component.js, src/templates/speciality.js, src/templates/speciality/schemas.js
Made Training section on the Speciality Page optional. 
Added GQL query to query for CaseStudyV2
Minor CSS fix (missing semicolon) to enable `width:100%`
Note: the Training Schema is stupidly simple and assumes that if there's no training intro line, there's no training section. Happy to make it more detailed, but this seemed to be sufficient to do the job.
=> training is now optional on speciality page (also minor CSS fix)

src/components/Blog/MediumPostPreview.js, src/components/Common/BlogListing.js, src/components/Footer/links.js, src/pages/blog.js, stories/__snapshots__/storyshots.test.js.snap
removes engineering word from the urls.
replace 'https://medium.com/yld-engineering-blog' with 'https://medium.com/yld-blog'
=> change the blog link

src/components/Common/Head.js
Previously this was working and now twitter doesn't seem to want to pick up the images for case studies... removing these tags as og tags should  suffice.
These two tags fallback to their corresponding `og` tags so we can remove them.
=> remove twitter:img and twitter:card tag from head

src/components/Common/Head.js
This PR puts back the `https://` we previously had as I don't believe twitter et al can read urls without the protocol
=> add https to og:image url generation

src/components/Header/TopNav/LogoLink.js, src/components/Header/TopNav/index.js, src/components/Header/navLinksHelper.js, src/templates/speciality.js
Logo colour was already added a non required field in Contentful `Speciality` but not always filled.
=> CMS Speciality Logo Colours

src/components/Header/TopNav/LogoLink.js
Removed with width attribute in the gif logo and replaced it with height to match landing page logo
=> Make sure gif logo and landing page logo are the same dimensions

src/templates/speciality.js
Put a short summary of what you did here:
- Populate all the specialities in Contentful with the new seoMetaData:
entityTitle
title: (Recommended Page Title - SEO title from YLD Full Pages list excel spreadsheet)
description: current description within Contentful
keywords: (Keyword Target from YLD Full Pages list excel spreadsheet)
- Retrieve seoMetaData data within speciality template and pass to Head
=> Retrieve seoMetaData data within speciality template and pass to Head

src/pages/open-source.js
Populate open source page with the new seoMetaData.
Retrieve seoMetaData data within open source page and pass to Head
=> Retrieve seoMetaData data within open source page and pass to Head

src/templates/policy.js
Populate privacy, cookie & data retention policy pages with the new seoMetaData.
Retrieve seoMetaData data within privacy policy page and pass to Head
Refactored a tiny bit privacy policy page
=> Retrieve seoMetaData data within privacy policy page and pass to Head

src/components/Common/Events.js, src/pages/contact.js, src/pages/open-source.js, src/templates/speciality-component.js, src/templates/speciality.js, src/templates/speciality/methods.js, stories/Specialty.stories.js, stories/assets/speciality-data.js
Changes meetup events to query by speciality ID rather than working out if event name contains speciality.
A new field has been added to the meetup event content type, this specialities field enables us to attach specialities to this event which we then query for when rendering each speciality.
K8s Connect event: 
https://app.contentful.com/spaces/22g1lenhck4z/entries/4YAaFl6VtbTfq19b5VYjgn
Has references to [Kubernetes](https://deploy-preview-373--yldio.netlify.com/speciality/kubernetes/) and [DevOps Culture](https://deploy-preview-373--yldio.netlify.com/speciality/devops-culture/) which display the k8s connect event
=> 654 - Update speciality events logic

src/pages/case-study/central-working-changing-how-you-work.js, src/pages/case-study/learnerbly-accelerating-professional-growth.js, src/pages/our-work.js
I removed from fields from contentful in some case study templates which meant that the queries are failing on netlify. This SEO meta data fields have already been replaced recently with the SEO Meta Data content type
https://app.netlify.com/sites/yldio/deploys/5d79d1090ddb02a95b857ed6
This PR removes them
=> FIX - remove bad queries from case study and ourwork

src/functions/github.js, src/functions/oss/repos.js, src/functions/oss/utils.js, tests/unit/lambdas/github.test.js, tests/unit/lambdas/repos.test.js
- Update repo.js util to handle missing github data
- Update github.js lambda to report `missingRepos`
- Update tests for github.js and repo.js
The github lambda didn't handle missing github data so is breaking on prod. This is because we expected there to always be github data to match the contentful data, however when someone leaves the yld github org we start seeing missing data...
=> 685  fix broken github lambda

package.json, yarn.lock
Recent updates to contentful content type schema caused some issues within gatsby-source-contentful plugin relating to mismatch in typings. 
Error looks like this:
```
TypeError: entryItemFields[foreignReference.name].push is not a function
- normalize.js:390 foreignReferences.forEach.foreignReference
[yld.io]/[gatsby-source-contentful]/normalize.js:390:52
- Array.forEach
- normalize.js:365 entries.map.entryItem
[yld.io]/[gatsby-source-contentful]/normalize.js:365:27
- Array.map
- normalize.js:296 locales.forEach.locale
[yld.io]/[gatsby-source-contentful]/normalize.js:296:32
- Array.forEach
- normalize.js:271 Object.exports.createContentTypeNodes
[yld.io]/[gatsby-source-contentful]/normalize.js:271:11
- gatsby-node.js:169 contentTypeItems.forEach …
```
=> bump gatsby-source-contentful

package.json, src/pages/case-study/canon-giving-stories-a-new-form.js, src/pages/case-study/joyent-bringing-application-awareness-to-cloud.js, tests/e2e/training-page-test.js
After this, I think we can set the v2 ones to public, delete the old ones and then remove the NonTemplatedCaseStudy queries for `our-work`
=> migrate non-template case study sites to v2

src/templates/policy.js
Then we can convert the plain text sections to markdown bodies and then delete the section type
=> render policy body as md

src/components/Common/GetInTouch.js, stories/__snapshots__/getInTouch.stories.snapshot
Enables correct `mailto:` linking
=> HOTFIX - Change Link component to 'a' in footer contact us

.babelrc, .babelrc.js, src/functions/blogMethods/__tests__/filter-posts-to-process.test.js, src/functions/blogMethods/__tests__/get-all-contentful-blog-post.test.js, src/functions/blogMethods/__tests__/parse-xml-to-json.test.js, src/functions/blogMethods/__tests__/publish-to-contentful.test.js, src/functions/blogMethods/__tests__/transform-html-to-markdown.test.js, src/functions/blogMethods/__tests__/transform-meta-data.test.js, src/functions/blogMethods/__tests__/validate-mdx.test.js, src/functions/blogMethods/custom-mdx/__tests__/add-frontmatter.test.js, src/functions/blogMethods/custom-mdx/__tests__/index.test.js, src/functions/blogMethods/custom-mdx/__tests__/transform-iframes.test.js, src/functions/blogMethods/custom-mdx/__tests__/transform-image-data.test.js, src/functions/blogMethods/custom-mdx/__tests__/transform-strings.test.js, src/functions/blogMethods/custom-mdx/__tests__/upload-image-to-contentful.test.js, src/functions/blogMethods/custom-mdx/transform-strings.js, src/functions/blogMethods/get-all-contentful-blog-posts.js, src/functions/blogMethods/index.js
=> request all (if more than 1000) blog posts from Contentful

src/components/Homepage/OurWork.js
=> fix MoreWorkLink styling

src/components/Common/Contributions.js, src/components/Common/Repo/Repo.js, src/pages/index.js, src/pages/open-source.js, stories/Repo.stories.js
https://trello.com/c/WURUZC2p/754-open-source-contributions-consider-counting-commits-instead-of-prs
=> show numbers for all GitHub contributions

src/components/Service/WorkStage.js, src/components/Training/Formats.js, src/components/Typography/BodyPrimaryStyles.js
Fix the icon spacing inconsistency across the services pages
=> Fix icon spacing in services pages

gatsby-node.js, src/components/Common/BaseVideoLink.js, src/components/Common/BlogListing.js, src/components/Common/GetInTouch.js, src/components/Homepage/services.js, src/components/Service/IntroSection.js
Since every speciality fits inside a service (engineering, design, training or open-souce) the URL will have the service in it (`/:service/:speciality`) instead of using the `/speciality/speciality` as before, which caused some SEO issues since `/speciality` isn't a valid page.
=> Generate speciality URL with service slug instead of 'speciality'

src/components/Common/Tab.js, src/components/Training/course/CourseInfo.js
- Fix the outline around _Contact us_ button on training course modal
- Add an underline to the selected tab upon 1st render on the _About us_ page
=> Fix outlines and underlines

gatsby-config.js, gatsby-node.js
A new aliases parameter was added to Blog Post content type. For each alias a new rule will be added to redirect from the alias to the actual blogpost URL.
=> Blogposts URL aliases

src/components/Common/LogoGrid.js
Reduce logos size on mobile so it can fit 2 items per row.
=> Fit 2 logos per row on mobile

src/components/layout.js
> ‘Cloaking’ is where you show the end-user different content than you are showing to crawlers. This is a violation of Google’s Webmaster Guidelines and can result in a search penalty.
Since the footer isn't visible for the users inside a training course page (it's bellow the modal), remove it from the DOM tree.
=> Don't render footer on training course modals

src/components/Blog/post/Typography.js
Issue reported on [slack](https://yld.slack.com/archives/C176N3FD4/p1603288344000900).
We should have the same `::selection` CSS rules on every typography element.
=> fix: use same selection rules on body for headers

src/components/Header/utils/navLinks.js, src/pages/join-us.js
Hannah requested to standardize the About header section. We have `Join us` and `About Us`.
=> chore: capitalize join us header

src/components/Header/DesktopNav/StyledHeaderLink.js
Luis requested that the underline should be removed from the words at the top left of the page when you hover.
=> Remove underline on hover of left headers

README.md
Changes proposed:
- Add instruction to copy the `.env.example` file to `.env` (The user may know it, but it's faster to just copy the command instead of typing it manually)
- Fix typos 
Note: _It doesn't have a Trello ticket since the changes apply improvements to docs_
Note: _Not checked anything since the changes apply improvements to docs_
=> docs: fix typos and add env instruction

src/components/Common/JobLink.js, src/components/Common/JobsByLocation.js, src/components/Common/OpenPositions.js
Reworked components in order to group all the jobs in terms of their team rather than their location. Each job has a `category`, which in turn has a `team`, like we see in this [example](https://api.lever.co/v0/postings/yld?mode=json).
=> Divide join-us categories by team rather than location

src/components/pagePaths.js
Fixed key name, which had prevented links being made to the speciality pages.
The pages themselves are under `/{service}/{speciality}` not `/speciality/{speciality}` since [this PR](https://github.com/yldio/yld.io/pull/470). So the kubernetes page is at https://www.yld.io/engineering/kubernetes/
~~- [ ] Updating or creating a new page? Consider any SEO requirements such as:~~
~~- [ ] Does the page have an `h1` tag?~~
~~- [ ] Does the page have a correctly formed meta title?~~
~~- [ ] Does the page have a correctly formed meta description?~~
~~- [ ] Does the page have a unique `og:image` tag (if required)?~~
=> fix: update key to fix speciality links

.gitignore, src/components/Homepage/services.js
created a grid to show services in 2 columns for desktop screen. kept 1 column for smaller screens.
=> display services in 2 columns in desktop
